import matplotlib.pyplot as plt

def plot_GP_from_file(filename):
    n_values = []
    term_values = []

    # Read data from file
    with open(filename, 'r') as file:
        # Skip the header
        file.readline()
        # Read data line by line
        for line in file:
            n, term = map(int, line.strip().split('\t'))
            n_values.append(n)
            term_values.append(term)

    # Plot the graph as a stem plot
    plt.stem(n_values, term_values, linefmt='b-', markerfmt='bo', basefmt='r-')
    for i in range(len(n_values)):
        plt.text(n_values[i], term_values[i], f'({n_values[i]}, {term_values[i]})', verticalalignment='bottom', horizontalalignment='right', fontsize=8, color='black')
    plt.xlabel('Term Number n')
    plt.ylabel('Term Value x(n)')
    plt.grid(True)
    plt.show()

if __name__ == "__main__":
    filename = "gp_data.txt"  # Specify the filename generated by the C code
    plot_GP_from_file(filename)
