import matplotlib.pyplot as plt

def plot_GP_from_file(filename):
    n_values = []
    term_values = []

    # Read data from file
    with open(filename, 'r') as file:
        # Skip the header
        file.readline()
        # Read data line by line
        for line in file:
            n, term = map(int, line.strip().split('\t'))
            n_values.append(n)
            term_values.append(term)

    # Plot the graph
    plt.scatter(n_values, term_values, marker='o')
    for i in range(len(n_values)):
        plt.plot([n_values[i], n_values[i]], [0, term_values[i]], color='gray', linestyle='--')
    plt.title('Geometric Progression')
    plt.xlabel('Term Number')
    plt.ylabel('Term Value')
    plt.grid(True)
    plt.show()

if __name__ == "__main__":
    filename = "gp_data.txt"  # Specify the filename generated by the C code
    plot_GP_from_file(filename)

